CREATE TABLE funcionario (
	id_funcionario INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	cpf VARCHAR(11) NOT NULL UNIQUE,
	email VARCHAR(100) NOT NULL UNIQUE,
	nome VARCHAR(100) NOT NULL,
	telefone VARCHAR(11) NOT NULL,
	ativo BOOLEAN DEFAULT TRUE
);
